blank_issues_enabled: false
contact_links:
  - name: Installation Guide
    url: https://github.com/JimMarley420/spicetify-extension#installation
    about: Read the installation instructions before opening an issue
